# Generated by Django 5.1.4 on 2026-08-07 06:46

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.sales.models.invoice_pdf_upload_to),
        ),
    ]
