# Generated by Django 5.1.4 on 2026-08-12 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_day10_perf_indexes'),
        ('sales', '0002_sale_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-sale_date', '-id'], name='sales_sale_sale_da_cfa272_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['invoice_no'], name='sales_sale_invoice_5ca049_idx'),
        ),
    ]
