# Generated by Django 5.1.4 on 2026-08-24 10:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_sku_and_purchase_invoice'),
        ('sales', '0003_day10_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', Decimal('0'))), name='sale_amount_paid_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total_amount'))), name='sale_amount_paid_lte_total'),
        ),
    ]
