# Generated by Django 5.1.4 on 2026-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_day10_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='default', max_length=16, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
