# Generated by Django 5.1.4 on 2026-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailoutbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailoutbox',
            new_name='core_emailo_status_a125e4_idx',
            old_name='core_emailo_status_7a2c1d_idx',
        ),
    ]
