# Generated by Django 5.1.4 on 2026-08-12 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0002_day10_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['-created_at', '-id'], name='inventory_a_created_0c6106_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['product', '-created_at'], name='inventory_a_product_f17d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at', 'id'], name='inventory_s_product_e4cc72_idx'),
        ),
    ]
