# Generated by Django 5.1.4 on 2026-07-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_financial_reports', 'Can view financial reports (margin, valuation, P&L)'), ('view_operational_reports', 'Can view operational reports (stock, low stock)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
