# Generated by Django 5.1.4 on 2026-08-12 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_day10_perf_indexes'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['-purchase_date', '-id'], name='purchases_p_purchas_9a18de_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier_invoice_no'], name='purchases_p_supplie_7267bc_idx'),
        ),
    ]
